# ------------ XDC MAP for Arty A7-35T ------------

ARTY_COMPS_i = {
    "BTN0"      :  "set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "BTN1"      :  "set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "BTN2"      :  "set_property -dict { PACKAGE_PIN B9    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "BTN3"      :  "set_property -dict { PACKAGE_PIN B8    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "SW0"       :  "set_property -dict { PACKAGE_PIN A8    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "SW1"       :  "set_property -dict { PACKAGE_PIN C11   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "SW2"       :  "set_property -dict { PACKAGE_PIN C10   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "SW3"       :  "set_property -dict { PACKAGE_PIN A10   IOSTANDARD LVCMOS33 } [get_ports { x }];",
}
ARTY_COMPS_o = {
    "LD0_b"     :  "set_property -dict { PACKAGE_PIN E1    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD0_g"     :  "set_property -dict { PACKAGE_PIN F6    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD0_r"     :  "set_property -dict { PACKAGE_PIN G6    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD1_b"     :  "set_property -dict { PACKAGE_PIN G4    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD1_g"     :  "set_property -dict { PACKAGE_PIN J4    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD1_r"     :  "set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD2_b"     :  "set_property -dict { PACKAGE_PIN H4    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD2_g"     :  "set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD2_r"     :  "set_property -dict { PACKAGE_PIN J3    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD3_b"     :  "set_property -dict { PACKAGE_PIN K2    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD3_g"     :  "set_property -dict { PACKAGE_PIN H6    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD3_r"     :  "set_property -dict { PACKAGE_PIN K1    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD4"       :  "set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD5"       :  "set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD6"       :  "set_property -dict { PACKAGE_PIN T9    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "LD7"       :  "set_property -dict { PACKAGE_PIN T10   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[1]"     :  "set_property -dict { PACKAGE_PIN G13   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[2]"     :  "set_property -dict { PACKAGE_PIN B11   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[3]"     :  "set_property -dict { PACKAGE_PIN A11   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[4]"     :  "set_property -dict { PACKAGE_PIN D12   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[5]"     :  "set_property -dict { PACKAGE_PIN D13   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[6]"     :  "set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[7]"     :  "set_property -dict { PACKAGE_PIN A18   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JA[8]"     :  "set_property -dict { PACKAGE_PIN K16   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_p[1]"   :  "set_property -dict { PACKAGE_PIN E15   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_n[1]"   :  "set_property -dict { PACKAGE_PIN E16   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_p[2]"   :  "set_property -dict { PACKAGE_PIN D15   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_n[2]"   :  "set_property -dict { PACKAGE_PIN C15   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_p[3]"   :  "set_property -dict { PACKAGE_PIN J17   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_n[3]"   :  "set_property -dict { PACKAGE_PIN J18   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_p[4]"   :  "set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JB_n[4]"   :  "set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_p[1]"   :  "set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_n[1]"   :  "set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_p[2]"   :  "set_property -dict { PACKAGE_PIN V10   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_n[2]"   :  "set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_p[3]"   :  "set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_n[3]"   :  "set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_p[4]"   :  "set_property -dict { PACKAGE_PIN T13   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JC_n[4]"   :  "set_property -dict { PACKAGE_PIN U13   IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[1]"     :  "set_property -dict { PACKAGE_PIN D4    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[2]"     :  "set_property -dict { PACKAGE_PIN D3    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[3]"     :  "set_property -dict { PACKAGE_PIN F4    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[4]"     :  "set_property -dict { PACKAGE_PIN F3    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[5]"     :  "set_property -dict { PACKAGE_PIN E2    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[6]"     :  "set_property -dict { PACKAGE_PIN D2    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[7]"     :  "set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports { x }];",
    "JD[8]"     :  "set_property -dict { PACKAGE_PIN G2    IOSTANDARD LVCMOS33 } [get_ports { x }];",
}
XDC_ENCODS = {
    "default": "## Clock signal \nset_property PACKAGE_PIN E3 [get_ports {clock}] \nset_property IOSTANDARD LVCMOS33 [get_ports {clock}]",
    "clk":"# Clock constraints \ncreate_clock -period x [get_ports {clock}]",  
}
